# Generated by Django 5.1.1 on 2024-10-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=200)),
                ('tg_chat', models.CharField(max_length=200)),
                ('tg_message', models.TextField()),
            ],
        ),
    ]
