# Generated by Django 5.1.1 on 2024-10-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
    ]
