# Generated by Django 5.1.1 on 2024-10-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
