# Generated by Django 5.1.1 on 2024-10-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoimost',
            name='name',
        ),
        migrations.DeleteModel(
            name='ServicePrice',
        ),
        migrations.DeleteModel(
            name='Stoimost',
        ),
    ]
